name: E2E Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: avivzgolan/github-actions-course-example-e2e
          ref: master
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run E2E tests
        run: npm run test:e2e
